defaults: &defaults
 adapter: mysql
 username: root
 password: 
 host: localhost

development:
 database: flockup_dev
 <<: *defaults

test:
 database: flockup_test
 <<: *defaults

production:
 database: flockup_production
 <<: *defaults