<% PASSWORD_FILE = File.join(RAILS_ROOT, '..', '..', 'shared', 'config', 'dbpassword') %>

defaults: &defaults
 adapter: mysql
 username: root
 password: 
 host: localhost

development:
 database: flockup_dev
 <<: *defaults

test:
 database: flockup_test
 <<: *defaults
 
staging:
  <<: *defaults
  database: flockup_staging
  username: flockup
  password: <%= File.read(PASSWORD_FILE).chomp if File.readable? PASSWORD_FILE %>
  encoding: utf8
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql
  database: flockup_production
  username: flockup
  password: mlzkxcvmpoiqwnjkladsng
  encoding: utf8
  socket: /var/run/mysqld/mysqld.sock