defaults: &defaults
 adapter: mysql
 username: root
 password: 
 host: localhost

development:
 database: APPNAME_dev
 <<: *defaults

test:
 database: APPNAME_test
 <<: *defaults

production:
 database: APPNAME_production
 <<: *defaults