defaults: &defaults
 adapter: mysql
 username: root
 password: 
 host: localhost

development:
 database: flockup_dev
 <<: *defaults

test:
 database: flockup_test
 <<: *defaults
 
production:
  adapter: mysql
  database: flockup_production
  username: flockup
  password: mlzkxcvmpoiqwnjkladsng
  encoding: utf8
  socket: /var/run/mysqld/mysqld.sock
