defaults: &defaults
 adapter: mysql
 username: root
 password: 
 host: localhost

development:
 database: flockup_dev
 <<: *defaults

test:
 database: flockup_test
 <<: *defaults
 
staging:
  adapter: mysql
  database: <%= PROJECT_NAME %>_staging
  username: <%= PROJECT_NAME %>
  password: <%= File.read(PASSWORD_FILE).chomp if File.readable? PASSWORD_FILE %>
  host: localhost
  encoding: utf8
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql
  database: <%= PROJECT_NAME %>_production
  username: <%= PROJECT_NAME %>
  password: <%= File.read(PASSWORD_FILE).chomp if File.readable? PASSWORD_FILE %>
  host: localhost
  encoding: utf8
  socket: /var/run/mysqld/mysqld.sock